# Performs reconstruction using the stereoBM algorithm

## On raw images

In [60]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
img_id = str(1)
img_name = './data/camera_0/jibo_capture_{}.png'.format(img_id)

print(img_name)
imgL = cv.imread('./data/camera_1/jibo_capture_{}.png'.format(img_id),0)
print(imgL)
#cv.imshow('img',imgL)
#cv.waitKey(5000)
imgR = cv.imread('./data/camera_0/jibo_capture_{}.png'.format(img_id),0)
#cv.imshow('img',imgR)
#cv.waitKey(5000)
stereo = cv.StereoBM_create(numDisparities=32, blockSize=7,preset=cv.FISHEYE_PRESET)
disparity = stereo.compute(imgL,imgR)
plt.imshow(disparity,'gray')
plt.show()

./data/camera_0/jibo_capture_1.png
[[ 59  57  57 ...  75  74  75]
 [ 57  57  55 ...  76  75  77]
 [ 57  57  58 ...  76  77  79]
 ...
 [ 71  74  75 ... 113 113 111]
 [ 72  74  75 ... 114 113 112]
 [ 72  75  76 ... 116 115 113]]


AttributeError: module 'cv2.cv2' has no attribute 'CV_FISHEYE_PRESET'

## On calibrated images

In [53]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
img_id = str(2)
img_name = './data/camera_0/jibo_capture_{}.png'.format(img_id)

print(img_name)
imgL = cv.imread('./data/camera_0/calibresult.png',0)
print(imgL)
#cv.imshow('img',imgL)
#cv.waitKey(5000)
imgR = cv.imread('./data/camera_1/calibresult2.png',0)
#cv.imshow('img',imgR)
#cv.waitKey(5000)
stereo = cv.StereoBM_create(numDisparities=128, blockSize=5)
disparity = stereo.compute(imgL,imgR)
plt.imshow(disparity,'gray')
plt.show()

./data/camera_0/jibo_capture_2.png
None


error: OpenCV(4.1.1) /io/opencv/modules/calib3d/src/stereobm.cpp:1114: error: (-211:One of the arguments' values is out of range) SADWindowSize must be odd, be within 5..255 and be not larger than image width or height in function 'compute'
